### ISSUE TITLE
babel-loader doesn't transpile imported js from an outside directory

### ISSUE THREAD

**Issue by felixexter** [babel/babel-loader#293] opened 2016-08-25 19:35 UTC
**Webpack Version:** 1.13.2
**Babel Core Version**: 6.14.0
**Babel Loader Version**: 6.2.5
**Environment:** Windows 7

I'm trying to import a script from an outside app directory

``` js
// app/scripts/app.js
import test from '../../../test'

// ../test/index.js
import muliply from './multiply'
export default (a, b) => muliply(a, b)
```

It should be transpiled to es5, but i get an error in browser console:

```
Uncaught SyntaxError: Unexpected token import
```

Is it a bug or a feature and I need to config something else?

**Comment by ericclemmons** [comment] 2016-08-25 19:37
Can you post up your config for `babel-loader`? Because this structure should be fine:

```
app/
test/
webpack.config.js
```

I've never a script import something _outside_ of an entire project.  (That's what `node_modules` is fore)

**Comment by felixexter** [comment] 2016-08-25 19:43
This structure
```
| project
| |- app/
| |- webpack.config.js
|- test/
  |- index.js
```

`.babelrc`
```
{
	"ignore": [
		"node_modules/**/*"
	],
	"presets": [
		"es2015",
		"stage-0"
	],
	"plugins": [
		"transform-runtime"
	]
}
```

**Comment by ericclemmons** [comment] 2016-08-25 21:50
Hmm, maybe Babel isn't the one processing it. (This directory structure is unorthodox, since files are being referenced _outside_ of `process.cwd()`).

Does it work if you run `webpack --config project/webpack.config.js`?

**Comment by abouthiroppy** [comment] 2016-08-26 00:53
Please rewrite below for `webpack.config.js`.

```
{
// ...
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      }
    ]
  }
// ...
}
```

How is it?

**Comment by felixexter** [comment] 2016-08-26 08:50
@abouthiroppy yes, it's same code, i just copied part of code, updated below
@ericclemmons no, it doesn't work, update structure below, each directory have node_modules, i run `webpack --config webpack.config.js` in project

**Comment by abouthiroppy** [comment] 2016-08-26 12:25
@felixexter Are you writing `modules` in `webpack.config.js` ? (I think I look at your updated comment)

**Comment by felixexter** [comment] 2016-08-26 12:48
@abouthiroppy fixed below, I write `module` :)

**Comment by abouthiroppy** [comment] 2016-09-09 04:56
@felixexter Sorry for my late reply. Did you solve this problem?

**Comment by felixexter** [comment] 2016-09-09 13:04
@abouthiroppy no

**Comment by kevincaradant** [comment] 2016-09-12 21:30
Hi :), I think I get the same problem today. Just to know, for me all works well if i installed the babel-loader (version 5.0.0) instead of 6.2.X. Is it the same for you ? Thank you

**Comment by loganfsmyth** [comment] 2016-09-13 05:27
@felixexter What folder is your `.babelrc` in? Your directory structure with tests and source split into two separate modules is rather unusual. A `.babelrc` applies to all files inside the directory is it in, so unless you've got the presets installed in both `tests` and `app` with a `.babelrc` in both directories, you'll definitely get the error you are seeing.

**Comment by eugene1g** [comment] 2016-09-27 21:43
Sometimes it helps to add a `.babelrc` file into the 'external' folder which points to your main config like so `{extends: '../../mainroot/.babelrc'}`

**Comment by felixexter** [comment] 2016-10-28 21:27
@kevincaradant No, it doesn't work for me.

**Comment by felixexter** [comment] 2016-10-28 21:30
@loganfsmyth `project` folder has `.babelrc`, `test` foder has one file `index.js` only.

**Comment by garaboo** [comment] 2016-11-22 09:55
@felixexter Try to place `.babelrc` into the `app` folder

**Comment by inkorcoder** [comment] 2017-01-23 22:05
I had the same problem. `npm i babel-loader@5` works for me, thanks!

**Comment by JasonRowe** [comment] 2017-02-01 05:45
I ran into this also. Going to try downgrading to see if it helps.

**Comment by samsul003** [comment] 2017-03-15 13:25
Hi, i have the same issue. I have asked a question in stackoverflow to see if anyone has a solution for that. 
[here is the question i asked in stackoverflow:](http://stackoverflow.com/questions/42808911/webpack-babel-es2015-error-uncaught-syntaxerror-unexpected-token-import)

> my package.json:
```
    "babel-core": "^6.22.1",
    "babel-loader": "^5.0.0",
    "babel-preset-es2015": "^6.22.0"
```

> my webpack.config.js
```
module.exports = {
  entry: {
    app: "./app/assets/scripts/App.js"
  },
  output: {
    path: "./app/temp/scripts",
    filename: "App.js"
  },
  module: {
    loaders: [
      {
        loader: 'babel-loader',
        query: {
          presets: ['es2015']
        },
        test: /\.js$/,
        exclude: /node_modules/
      }
    ]
  }
}

```

> and my .babelrc (project root dir)
```
{
  "presets": ["es2015"]
}

```

@inkorcoder 
i tried to install babel-loader@5.0.0 but still no luck !
@kevincaradant 
hey man, u said u solved it but how?

**Comment by kevincaradant** [comment] 2017-03-15 13:38
@samsul003, Hi, really sorry but I didn't remember, and when I see my answer,  I don't know. I think the configuration suggested in my previous message is the thing which resolved my problem but maybe it's not the case of everyone :/

**Comment by samsul003** [comment] 2017-03-15 15:29
Hi, i got it solved. As it seems to me it doesnt really matter which version of the babel core, babel-loader you actually use. Also .babelrc file was not required for me. What worked for me was to include the bundled file in my HTML which was generated at temp/scripts/App.js, instead of including the original source at assets/scripts/App.js. Thats it ! cheers

**Comment by MichaelMammoliti** [comment] 2017-04-08 17:28
Remember to include the input file and not the output.

this: 
```<script src='app/index.js'></script>```

to:
```<script src='bundle/bundle.js'></script>```

**Comment by mareksuscak** [comment] 2017-06-01 15:58
Ran into a similar issue today. This was my folder structure:

```
root/
  node_modules/
  lib/
    dep.js
  demo/
    node_modules/
      babel-preset-es2015
    .babelrc
    entry.js
    package.json
    webpack.config.js
  package.json
```

Now, `entry.js` was importing `../lib/dep.js`. Here's the loader configuration (webpack2):

```json
{
  test: /\.js$/,
  loader: 'babel-loader',
  exclude: /node_modules/
}
```

The solution that helped me was to remove `.babelrc` file and move the options to `webpack.config.js` as such:

```json
{
  test: /\.jsx?$/,
  use: {
    loader: 'babel-loader',
    options: {
      presets: [
        require.resolve('babel-preset-react'),
        [require.resolve('babel-preset-es2015'), { "modules": false }],
        require.resolve('babel-preset-stage-0')
      ]
    }
  },
  exclude: /node_modules/
}
```

I suspect there's a problem with package paths if you don't resolve the path at build time.

**Comment by monkindey** [comment] 2017-07-13 06:44
@felixexter I also Ran into a similar issue. When I tried to find the reason, I add the console.log and it word. Maybe you can try it.

```js
// ../test/index.js
import muliply from './multiply'
console.log('The strange bug');
export default (a, b) => muliply(a, b)
```

**Comment by mass85** [comment] 2017-07-25 09:10
I have a similar issue when imported module is linked. In order to isolate it I created a simple project: https://github.com/mass85/no_transpilation_with_lerna

Could anyone be so kind and have a look at this and try to fix it?

**Comment by jamescoq** [comment] 2017-08-21 10:53
I have the same issue as @mass85. 
When importing JS file from a simlinked module in lerna monorepo I get error
`Unexpected token (6:4)
You may need an appropriate loader to handle this file type.
| export default {
|   en: {
|     ...en
|   },
|   cs: {
`
when remove the simlink and copy the files, then it woks fine.

**Comment by richburdon** [comment] 2017-11-14 01:37
This just started happening with me using a yarn monorepo.

Previously, the problem was resolved by adding the appropriate (linked) paths to the webpack `include` param for the `babel-loader`. But this no longer works (doesn't seem to matter if they are linked or hard copied).

E.g., 

~~~~
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        include: [
          path.resolve('.'),
          path.resolve('../registry'),            // Linked modules.
          path.resolve('../util')
        ],
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: './dist/babel-cache/'
          }
        }
      }
    ]
  }
~~~~

**Comment by loganfsmyth** [comment] 2017-11-14 01:49
Have you updated to a new Webpack version or anything?

**Comment by richburdon** [comment] 2017-11-14 01:54
I resolved my issue and may have a solution for folks (Webpack 2).
My webpack config above does in fact work for me (I had a gnarly bug where one of my JS files actually had a different file suffix -- really hard to find).

If you're in doubt install `echo-loader` and add that to the babel-loader config. When running webpack it will output each file that is visited. You should see whether the file is transpiled or not.

~~~~
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        include: [
          path.resolve('.'),
          path.resolve('../registry'),            // Linked module.
        ],
        use: [{
          loader: 'echo-loader',
        }, {
          loader: 'babel-loader',
          options: {
            cacheDirectory: './dist/babel-cache/'
          }
        }]
      }
    ]
  }
~~~~

**Comment by thedamon** [comment] 2017-11-27 18:27
I have a very similar issue in a monorepo. Adding a .babelrc to the exterior file's parent and that started it working, but a different build broke because it was using an old version of babel that doesn't support `"presets"` as an option :|. My solution so far is that this build doesn't get minified and that we obviously have bigger structural problems to worry about.

**Comment by ericclemmons** [comment] 2017-12-30 00:16
I ran into the same issue today!  The example repo (https://github.com/mass85/no_transpilation_with_lerna) does a good job capturing the problem.

I did notice (along with @thedamon) that when I move `.babelrc` up into the monorepo root, things get _closer_, but it creates problems with other projects that end up keying off of that `.babelrc` then =/

One thing that seemed to have helped was explicitly setting the `options` & removing the `.babelrc` entirely:

```js
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: [
          path.resolve(__dirname, "src"),
          path.resolve(__dirname, "../../packages"),
        ],
        query: Object.assign(
          {
            babelrc: false,
            cacheDirectory: false,
          }
          require("./my-babel-preset")
        ),
      }
```

**Comment by piranna** [comment] 2018-02-24 10:43
I have a similar problem, hope it helps.

I have an app project that builds successfully, and I have it as dependency of an `Integration` project (forr global tests and showcases), that fails, also having all app project `devDependencies` set as `dependencies` for both the app and the Integration projects. Only solution I've found so far is to go into the `node_modules/<app>` forlder and exec `npm install` there, so the dependencies (babel-loader and friends) are at the app project root folder and NOT at its parent `Integration` project. This shows me that `babel` or `babel-loader` search for plugins on the `node_modules` folder of the current project root and not search towards its parent dirs, although the Node.js modules path resolution allows this. I think what's proposed at https://github.com/babel/babel-loader/issues/293#issuecomment-305538738 would fix this for me, that would confirm that so I'll try to look at it later. Maybe would only it needed to have the `babel-preset-env` module installed inside the app project?

**Comment by renatonmendes** [comment] 2018-03-14 12:57
Is this problem solved ? I´m running the same issue as @felixexter

**Comment by richardtallent** [comment] 2018-03-20 03:56
Having the same problem here. I have two repos -- a Vue component, and a demo/test site for said component. I want to have them pulled in sister folders and use the demo site to test live changes I'm making in the Vue components.

**Comment by Morphexe** [comment] 2018-03-25 02:41
The same issue going on, I have a utility that needs to import Class File from a package outside the folder ( Its model definition for a database) from a sister project,

 I mean, it should just transpile the imported file as if it was same dir import, I can't see why this does not work out of the box, to be honest.

**Comment by ViBiOh** [comment] 2018-03-29 07:19
I have the same issue here, I resolved with this tricks:

**Comment by ViBiOh** [comment] 2018-03-29 07:22
I had the same issue here, I wanted to keep my `.babelrc` (for editor and clearness) so the config was:

`webpack.config.js`

```js
const babelConfig = JSON.parse(fs.readFileSync('.babelrc'));

...

{
    test: /\.js$/,
    exclude: /node_modules/,
    use: {
        loader: 'babel-loader',
        options: {
          presets: babelConfig.presets.map(preset => [require.resolve(`babel-preset-${preset}`), { "modules": false }]),
          plugins: babelConfig.plugins.map(plugin => require.resolve(`babel-plugin-${plugin}`)),
        }
    },
},
```

No config needed in external folder, and my `.babelrc` contains

```
{
  "presets": ["env"],
  "plugins": [
    "transform-class-properties",
    "transform-runtime"
  ]
}
```

**Comment by good-idea** [comment] 2018-05-06 23:59
I have the same issue with a monorepo, and my working solution is adapted from @ViBiOh's above:

```js
{
	loader: 'babel-loader',
	options: {
		presets: babelConfig.presets.map((preset) => [preset, { modules: false }]),
		plugins: babelConfig.plugins.map((plugin) => {
			if (typeof plugin === 'string') return plugin
			return [...plugin]
		}),
	},
},
```

.babelrc:
```js
{
	"presets": ["@babel/preset-react", "@babel/preset-flow", "@babel/preset-env"],
	"env": {
		"development": {
			"plugins": ["flow-react-proptypes"]
		}
	},
	"plugins": [
		[
			"babel-plugin-module-resolver",
			{
				"root": ["./app"],
				"extensions": [".js", ".web.js", ".native.js"],
				"alias": {
					"App": "./app/"
				},
				"cwd": "babelrc"
			}
		],
		"babel-plugin-styled-components",
		"@babel/plugin-proposal-class-properties",
		"@babel/plugin-proposal-object-rest-spread",
		"react-hot-loader/babel",
		"ramda"
	]
}
```

My solution was a little different because one of my plugins has configuration options.

I should also note that this doesn't use `require.resolve()` and it's working fine. If I do use it, there's an error loading `babel-plugin-ramda`. I'm not sure if the issue lies with babel or the plugin.

```
ERROR in ./app/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/joseph/Sites/myProject/beta/node_modules/ramda/src/index.js
    at createDescriptor (/Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-descriptors.js:181:11)
    at /Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-descriptors.js:106:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-descriptors.js:105:27)
    at createPluginDescriptors (/Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-descriptors.js:92:12
    at cachedFunction (/Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/caching.js:42:17)
    at plugins (/Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-descriptors.js:23:61)
    at mergeChainOpts (/Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-chain.js:369:68)
    at /Users/joseph/Sites/myProject/beta/node_modules/@babel/core/lib/config/config-chain.js:324:7
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill react-hot-loader/patch webpack-dev-server/client?https://localhost:8080 webpack/hot/only-dev-server ./app/index.js
```

**Comment by mqliutie** [comment] 2018-05-29 09:43
Hi, in my case I have two entry files called `a.js` and `b.js`.

`a.js` is **es6** code 
`b.js` imported `a.js`


I need `b.js` using `presets-es2015` but `a.js` not. in other words `b.js` will be **es5**  code `a.js` still `es6`
I also ask question in [stackoverflow](https://stackoverflow.com/questions/50580636/webpack-set-two-entry-files-called-a-and-b-js-one-no-presets)

**Comment by robatwilliams** [comment] 2018-06-15 15:20
Workaround for when this problem arises when depending on a sibling lerna package: `resolve.symlinks: false` in webpack config

**Comment by loganfsmyth** [comment] 2018-09-02 00:03
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

The issue is that `.babelrc` files do not affect files in sibling folders. With Babel 6, you'd need to pass your config via `babel-loader`'s options. For Babel 7, you can consider using a [project-wide `babel.config.js`](http://babeljs.io/docs/en/config-files#project-wide-configuration)

**Closed by loganfsmyth** 2018-09-02 00:03 UTC

**Comment by antriver** [comment] 2019-02-07 22:09
I had this same issue and tried a few fixes here that didn't solve it.

My directory structure is:
parent
    project-1
    project-2

project-1 imported some modules from project-2 (temporarily!) and was erroring because the 'babel-plugin-transform-object-rest-spread' plugin was not working.

My parent/project-1/webpack.config.js used to be:
```
module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        babelrc: true,
                    },
                },
            },`
```
And parent/project-1/.babelrc
```
{
    "presets": [
        "babel-preset-env"
    ],
    "plugins": [
        "babel-plugin-transform-object-rest-spread",
        "babel-plugin-syntax-dynamic-import"
    ]
}
```

It started working by removing `babelrc:true` from the webpack config and putting the options in the webpack config instead:

```
module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['babel-preset-env'],
                        plugins: [
                            "babel-plugin-transform-object-rest-spread",
                            "babel-plugin-syntax-dynamic-import"
                        ]
                    },
                },
            },
```

You also must have the babel plugins installed in both project-1/node_modules and project-2/node_modules.

**Comment by ShineKidd** [comment] 2019-07-03 09:51
> @felixexter Try to place `.babelrc` into the `app` folder
```
|- project
| |- app/
| |- node_modules/
| |- webpack.config.js
|- test/
  |- node_modules/
  |- index.js
|- .babelrc 
```

**Comment by revanth0212** [comment] 2020-01-09 17:44
My fix was to add another route to the includes array. I was referencing certain file from another package outside my current package, so did this for both JS and CSS rules in `webpack.config.js`:

Before

`resolve(__dirname, 'src')`

After

`[resolve(__dirname, 'src'), resolve(__dirname, '..', ANOTHER_PACKAGE, 'src')]`
