### ISSUE TITLE
babel-loader 8.0.0 fails, but 8.0.0-beta.4 works perfectly

### ISSUE THREAD

**Issue by Slapbox** [babel/babel-loader#665] opened 2018-08-29 16:38 UTC
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**
**I'm submitting a feature request**
**I'm submitting a support request** => Please do not submit support request here, see note at the top of this template.

**Webpack Version:**
4.17.1

**Babel Core Version**:
7.0.0

**Babel Loader Version**:
8.0.0

**Please tell us about your environment:**
Windows 7 x64

**Current behavior:**
Here's just a small sample of the very long list of console messages.
**First message - error:**
```
storage.js:26 Uncaught ReferenceError: exports is not defined
    at Module.<anonymous> (storage.js:26)
    at Module../app/utils/electron/storage.js (renderer.dev.js:34068)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Module../app/utils/electron/index.js (renderer.dev.js:33851)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Module.<anonymous> (renderer.dev.js:22555)
    at Module../app/index.js (renderer.dev.js:22738)
    at __webpack_require__ (bootstrap:724)
```
**followed by these warnings:**
```
(anonymous) @ storage.js:26
./app/utils/electron/storage.js @ renderer.dev.js:34068
__webpack_require__ @ bootstrap:724
fn @ bootstrap:101
./app/utils/electron/index.js @ renderer.dev.js:33851
__webpack_require__ @ bootstrap:724
fn @ bootstrap:101
(anonymous) @ renderer.dev.js:22555
./app/index.js @ renderer.dev.js:22738
__webpack_require__ @ bootstrap:724
fn @ bootstrap:101
0 @ log.js:47
__webpack_require__ @ bootstrap:724
(anonymous) @ bootstrap:791
(anonymous) @ bootstrap:791
sockjs.js:1605 XHR finished loading: GET "http://localhost:1212/sockjs-node/info?t=1535560470291".
AbstractXHRObject._start @ sockjs.js:1605
(anonymous) @ sockjs.js:1494
setTimeout (async)
AbstractXHRObject @ sockjs.js:1493
XHRCorsObject @ sockjs.js:2871
InfoAjax @ sockjs.js:356
InfoReceiver._getReceiver @ sockjs.js:539
InfoReceiver.doXhr @ sockjs.js:556
(anonymous) @ sockjs.js:525
setTimeout (async)
InfoReceiver @ sockjs.js:524
SockJS @ sockjs.js:730
initSocket @ socket.js:9
(anonymous) @ client?5bf0:212
./node_modules/webpack-dev-server/client/index.js?http://localhost:1212 @ renderer.dev.js:50057
__webpack_require__ @ bootstrap:724
fn @ bootstrap:101
0 @ log.js:47
__webpack_require__ @ bootstrap:724
(anonymous) @ bootstrap:791
(anonymous) @ bootstrap:791
sockjs.js:1605 XHR finished loading: GET "http://localhost:1212/sockjs-node/info?t=1535560470293".
AbstractXHRObject._start @ sockjs.js:1605
(anonymous) @ sockjs.js:1494
setTimeout (async)
AbstractXHRObject @ sockjs.js:1493
XHRCorsObject @ sockjs.js:2871
InfoAjax @ sockjs.js:356
InfoReceiver._getReceiver @ sockjs.js:539
InfoReceiver.doXhr @ sockjs.js:556
(anonymous) @ sockjs.js:525
setTimeout (async)
InfoReceiver @ sockjs.js:524
SockJS @ sockjs.js:730
initSocket @ socket.js:9
(anonymous) @ client?8f77:212
./node_modules/webpack-dev-server/client/index.js?http://localhost:1212/ @ renderer.dev.js:50317
__webpack_require__ @ bootstrap:724
fn @ bootstrap:101
0 @ log.js:47
__webpack_require__ @ bootstrap:724
(anonymous) @ bootstrap:791
(anonymous) @ bootstrap:791
client?5bf0:77 [WDS] Hot Module Replacement enabled.
client?5bf0:148 [WDS] Warnings while compiling.
warnings @ client?5bf0:148
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
client?5bf0:154 ./app/redux/actions/helpScreen_actions.js 19:10-35
```
the list of warnings was very long. This is far from all of them.

**Expected/desired behavior:**
No errors - as in 8.0.0-beta.4

**Comment by loganfsmyth** [comment] 2018-08-29 16:53
This seems like it could be the same issue as https://github.com/babel/babel-loader/pull/660#issuecomment-416738962 with the issue being https://github.com/babel/babel-loader/pull/660#issuecomment-416755183

The issue is either
* storage.js is using both ES6 `import` syntax _and_ Commonjs `exports` objects
* You're using `transform-runtime`, which is inserting an `import` into a CommonJS file because you have not configured Babel's `sourceType` option.

You can always opt into the old behavior by setting `modules: "commonjs"` in your `preset-env` options, but otherwise I'd avoid using CommonJS `exports` and `import` and/or set `sourceType: "unambiguous"`

**Comment by Slapbox** [comment] 2018-08-29 17:26
Thanks for your reply @loganfsmyth 

I'm not using `transform-runtime` and I don't think I'm mixing syntaxes, can you let me know if I'm mistaken?

This is what that file looks like:

```js
import _ from 'lodash';

// Other stuff

export default function() {
  return next => (reducer, initialState) => {
    const store = next(reducer, initialState);
    store.subscribe(() => {
      const state = store.getState();
      throttledSaveState(state);
    });
    return store;
  };
}
```

**Comment by loganfsmyth** [comment] 2018-08-29 17:28
Hmm, I'm not sure then. If you have a reproducible example I can look more closely.

**Comment by Slapbox** [comment] 2018-08-29 17:36
For now I'll sit back on 8.0.0-beta.4. I'll try to provide some code for reproducing this if it remains an issue in a few weeks when I have some more time.

Thanks for your help @loganfsmyth.

**Comment by loganfsmyth** [comment] 2018-08-29 17:43
Fair enough! It definitely seems like a mismatch of module types somewhere from something, but it's hard to say exactly.

**Comment by Klupzor** [comment] 2018-08-30 04:33
I have the same problem, I had to install version 7.1.4

**Comment by loganfsmyth** [comment] 2018-08-30 16:33
@Klupzor Without more information, it's hard to give suggestions. Chances are there is something that would need to change in your configuration.

**Comment by loganfsmyth** [comment] 2018-08-30 18:28
The big change is https://github.com/babel/babel-loader/pull/660 because now you're relying on Webpack to transform modules instead of Babel. This raises two primary cases that can cause trouble:

* Webpack is stricter than Babel around spec compliance of modules
* Babel may need to have `sourceType` configured carefully if you're using `transform-runtime` or `preset-env`'s `useBuiltins`

**Comment by teodosii** [comment] 2018-08-30 18:55
> storage.js is using both ES6 import syntax and Commonjs exports objects

What would be the fix in this case? I'm using both ES6 import and exports. Using exports in order to mock in same module, otherwise I cannot mock functions.

I've recently updated to babel-loader and I've got the same problem with `exports is not defined`

**Comment by loganfsmyth** [comment] 2018-08-30 19:08
You can always opt into the old behavior by setting modules: "commonjs" in your preset-env options to get the old behavior for now.

Generally mixing module types is a bad idea. Mocking depends a bit on what test framework you're using, but for instance Jest as [`jest.mock`](https://jestjs.io/docs/en/manual-mocks#mocking-node-modules).

**Comment by teodosii** [comment] 2018-08-30 19:50
I didn't know it is a bad idea mixing import/exports. Thing is if I need to mock a function in the same module, the only way it worked for is by referencing that function in `/src` using `exports` syntax and then in Jest I simply

`import * as Helpers from '/src/helpers'`

and then I just mock functions on `*` using `jest.fn` or `jest.mockImplementation`

And functions would be written like this

```
const g = () => { ... };
const f = () => { exports.g(); };
```

This way, by using `exports` I can mock it when running the test. I know it's not related to the issue here entirely, but I couldn't found any solutions to my problem other than the one I've said.

I guess I could go on by setting `commonjs` module but just in case I change my mind on this, do you know how can I mock it using a different approach in order not to mix import/exports?

**Comment by loganfsmyth** [comment] 2018-08-30 19:54
I'm not totally an expert there. I was under the impression `jest.mock` would work with ES `export` syntax.

**Comment by loganfsmyth** [comment] 2018-09-02 21:49
I'm going to close this since there doesn't appear to be anything clearly actionable. If you or someone else can get a clear reproduction case, feel free to re-open and ping me, or open a new issue.

**Closed by loganfsmyth** 2018-09-02 21:49 UTC

**Comment by SilentFlute** [comment] 2018-12-14 03:36
@Slapbox it seems u don't solve this problem yet……i occur this problem too, and i use
Webpack Version:
4.26.1

Babel Core Version:
7.0.0

Babel Loader Version:
8.0.4
`babel-loader^8.0.0` doesn't work neither……
seems like `babel` can't transpiled `export default`, well, it's `babel-loader^8.0.0+` can't do it actually……(may be)
until u said `babel-loader^8.0.0-beta.4` works perfectly, i tried install `babel-loader^8.0.0-beta.4` instead `babel-loader^8.0.0`:
Webpack Version:
4.26.1

Babel Core Version:
7.0.0

Babel Loader Version:
8.0.0-beta.4
it worked!!!!!!!!!!!!!!!!!!!!!
i don't know why, but it worked
thx
; )
