### ISSUE TITLE
loadPartialConfig fails to clear the overrides/test/include/exclude fields from its result

### ISSUE THREAD

**Issue by HsuTing** [babel/babel-loader#642] opened 2018-07-12 10:09 UTC
**I'm submitting a bug report**

**Webpack Version:**
3.10.0

**Babel Core Version**:
7.0.0-beta.53

**Babel Loader Version**:
8.0.0-beta.3

**Please tell us about your environment:**
OSX 10.13.5

**Current behavior:**
I give `configFile` as `options` like:
```js
...
options: {
  configFile: '../../babel.config.js',
},
...
```
And this will not get any `plugins` or `presets` with `babel.config.js`.

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
Just need to add `babel.config.js` to `options.configFile`.

* **What is the expected behavior?**
This should work with `babel.config.js`.

* **What is the motivation / use case for changing the behavior?**
I use `babel.config.js` in a `mono repo`. As a result, I want to `babel.config.js` can work, and I only need to write a config file to the root folder.

**Comment by loganfsmyth** [comment] 2018-07-12 15:42
> but the options of babel-core.transform need configFile.

What makes you say that? With the current setup, `config` should have everything that would have been read from the config file, so reading it again would be extra work.

**Comment by loganfsmyth** [comment] 2018-07-12 15:48
Would you be able to provide an repository with an example of the config not working? I can look into it.

**Comment by HsuTing** [comment] 2018-07-12 16:03
Maybe I misunderstand the function.
My repository is private, but I will try to make en example repository.
Thank you!

**Comment by HsuTing** [comment] 2018-07-12 16:38
@loganfsmyth Sorry, I found this error is not made by `configFile`.
When I used `overrides`, `overrides` will make this error.
[Here](https://github.com/HsuTing/example-babel-loader) is my example repository.
Hope this will help you.

**Comment by loganfsmyth** [comment] 2018-07-12 17:37
Perfect, thanks. I see just what the problem is now.

**Comment by loganfsmyth** [comment] 2018-07-13 02:44
I've posted https://github.com/babel/babel/pull/8315 which should address this once it is merged and published.

**Comment by HsuTing** [comment] 2018-07-13 02:45
OK!
Thank you 😁!

**Closed** 2018-07-13 14:01 UTC
