### ISSUE TITLE
Module parse failed: Unexpected token (7:18)You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by AnuragVnit** [babel/babel-loader#768] opened 2019-02-17 05:10 UTC
![screenshot from 2019-02-17 07-20-57](https://user-images.githubusercontent.com/4919924/52908586-d9b12e80-329e-11e9-9021-c3aaa50598e8.png)
webpack config
![screenshot from 2019-02-17 08-03-55](https://user-images.githubusercontent.com/4919924/52908589-e2096980-329e-11e9-9fb2-7949e4716db5.png)

I went through all the issues but nothing seemed to solved my problem
package.json

![screenshot from 2019-02-17 10-40-03](https://user-images.githubusercontent.com/4919924/52908666-66a8b780-32a0-11e9-8e00-4bc1daa04868.png)

**Comment by loganfsmyth** [comment] 2019-02-17 05:33
Duplicate of https://github.com/babel/babel-loader/issues/760.

**Closed by loganfsmyth** 2019-02-17 05:33 UTC
