### ISSUE TITLE
Syntax Error in JSX crashes process

### ISSUE THREAD

**Issue by jeremiahrhall** [babel/babel-loader#68] opened 2015-05-19 18:03 UTC
I'm using webpack-dev-server and babel-loader to compile a React application.

In babel-loader 5.1.0 and 5.1.2 syntax errors in JSX are causing the process to terminate after the error is logged.

I get the same behavior whether I use webpack-dev-server in my Node app or as a CLI.

In 5.0.0 I get the same stack trace but no process termination. Is there a new option to use or is this not desired?

**Comment by Couto** [comment] 2015-05-19 18:26
Can you post a snippet with the error log to help with debug?

**Comment by jeremiahrhall** [comment] 2015-05-19 18:36
Here's the output right before the process terminates:

webpack: bundle is now INVALID.
```
/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:600
      throw err;
            ^
SyntaxError: /Users/jeremiahrhall/Projects/hthu-web/web_loaders/fix-ie-loader.js!/Users/jeremiahrhall/Projects/hthu-web/hthu/app/dashboard/Dashboard.jsx: Unexpected token (79:8)
  77 | 
  78 |     render: function() {
> 79 |         >ASDAS!@#!@#$%
     |         ^
  80 |         return (
  81 |             <div id="mainContent" className="container dashboard">
  82 |                 <div className="row">
    at Parser.pp.raise (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseExprAtom (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:393:12)
    at Parser.parseExprAtom (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/node_modules/acorn-jsx/inject.js:624:24)
    at Parser.pp.parseExprSubscripts (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseExpression (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:81:19)
    at Parser.pp.parseStatement (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/statement.js:118:23)
    at Parser.parseStatement (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/plugins/flow.js:636:22)
    at Parser.pp.parseBlock (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
    at Parser.pp.parseFunctionBody (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:693:22)
    at Parser.parseFunctionBody (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/plugins/flow.js:624:20)
    at Parser.pp.parseFunction (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/statement.js:465:8)
```

And when I change to 5.0.0 I get essentially the same error but, it doesn't crash webpack-dev-server and presumably the NoErrorsPlugin doesn't emit the bundle to the client:

```
ERROR in ./~/transform-loader/cacheable.js?envify!./~/react-hot-loader!./~/babel-loader?{"cacheDirectory":true,"stage":0}!./web_loaders/fix-ie-loader.js!./hthu/app/dashboard/Dashboard.jsx
Module build failed: SyntaxError: /Users/jeremiahrhall/Projects/hthu-web/web_loaders/fix-ie-loader.js!/Users/jeremiahrhall/Projects/hthu-web/hthu/app/dashboard/Dashboard.jsx: Unexpected token (80:8)
  78 |     render: function() {
  79 |         
> 80 |         >ASDAS!@#!@#$%
     |         ^
  81 |             
  82 |         return (
  83 |             <div id="mainContent" className="container dashboard">
    at Parser.pp.raise (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseExprAtom (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:393:12)
    at Parser.parseExprAtom (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/node_modules/acorn-jsx/inject.js:624:24)
    at Parser.pp.parseExprSubscripts (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseExpression (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:81:19)
    at Parser.pp.parseStatement (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/statement.js:118:23)
    at Parser.parseStatement (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/plugins/flow.js:636:22)
    at Parser.pp.parseBlock (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
    at Parser.pp.parseFunctionBody (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/expression.js:693:22)
    at Parser.parseFunctionBody (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/plugins/flow.js:624:20)
    at Parser.pp.parseFunction (/Users/jeremiahrhall/Projects/hthu-web/node_modules/babel-loader/node_modules/babel-core/lib/acorn/src/statement.js:465:8)
 @ ./~/react-router-proxy-loader!./hthu/app/dashboard/Dashboard.jsx 7:28-459 35:28-459
webpack: bundle is now VALID.
```

**Comment by Couto** [comment] 2015-05-20 10:27
I have a suspicion of what it might be, but no matter what I do, I can't replicate the process termination.
Can you tell me the webpack-dev-server's version that you're using, and/or share your config file (if you can) ?

**Comment by akheron** [comment] 2015-05-20 12:45
This happens for me too with plain `webpack --watch`. Whenever one of the jsx files have a syntax error, the webpack process terminates and I have to restart it manually.

I'm not sure which version broke things, but this didn't happen before I updated babel-loader and babel-core yesterday. Now I'm using versions 5.1.2 and 5.4.4 respectively.

**Comment by akheron** [comment] 2015-05-20 12:56
I noticed that not using the `cacheDirectory` option makes the issue go away.

Here are reduced files to reproduce:

**webpack.config.js**
```js
'use strict';

var path = require('path');

module.exports = {
  entry: './app',
  output: {
    path: __dirname,
    filename: 'bundle.js'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'babel?cacheDirectory'
    }]
  }
};
```

**app.js**
```jsx
<foo>
```

**Comment by Couto** [comment] 2015-05-20 13:40
Ok. Not breaking without `cacheDirectory` is something new. That's cool. I will try to reproduce this with that option! :)

**Comment by Couto** [comment] 2015-05-20 14:08
I was able to reproduce the problem with `cacheDirectory`. On my tests the process is not being terminated when a `SyntaxError` happens. Can you test it? 

You can find it on npm with the version [5.1.3](https://github.com/babel/babel-loader/tree/v5.1.3)

**Comment by akheron** [comment] 2015-05-21 05:33
Works like a charm now. Thanks a lot for fixing!

**Comment by Couto** [comment] 2015-05-21 09:47
@akheron That's great news! 
@jeremiahrhall Is it still giving you problems, with the last update?

**Comment by vsolovyov** [comment] 2015-05-21 14:26
I experienced the same problem on 5.1.0 and I had `cacheDirectory` specified. With 5.1.3 works with no problems, thanks!

**Comment by Couto** [comment] 2015-05-22 06:42
I'm closing this.
If someone else still has the same problem I'll gladly re-open it.

Thanks everyone for the reports :+1:

**Closed by Couto** 2015-05-22 06:42 UTC

**Comment by tanu2626** [comment] 2017-02-11 13:31
@akheron webpack --watch, worked like magic. I was struggling since 2 hours. Thanks again 👍
