### ISSUE TITLE
Plugin transform-runtime with webpack doesn't work properly

### ISSUE THREAD

**Issue by jesprider** [babel/babel-loader#231] opened 2016-03-29 11:22 UTC
Trying to make working transform-runtime plugin within webpack babel-loader.

``` js
loaders: [{
      test:   /\.js$/,
      loader: 'babel-loader',
      query: {
        presets: ['es2015'],
        plugins: ['transform-runtime']
      }
    }]
```

Packages `babel-runtime` and `babel-plugin-transform-runtime` are both installed.

I have 2 different results in 2 different projects:
- On a real project it increase the size of file (is that fine?)
  ![babel-transform-runtime](https://cloud.githubusercontent.com/assets/5961288/14106352/d05b23fa-f5b0-11e5-972c-5eea966c5d78.png)
- Then I decided to test it within 2 simple files. No impacts. The same built file with and without the plugin.

Am I doing something wrong or there is a real bug there?

**Comment by loganfsmyth** [comment] 2016-03-29 15:34
The runtime transform only pulls in pieces that you use. Does your sample files use the same ES6 features that the main app does?

**Comment by jesprider** [comment] 2016-03-31 11:37
I rewrote the sample files a bit. Now I have `class Page` in `page.js`. `home.js` and `about.js` create instances of the `page` class. In app.js I import these two pages and call a method.

The result of building with `transform-runtime`: 5 additional modules in build file, weight is twice more.
Does it work how it supposed to work?

I put my sample app here with 2 different builds to compare:
[sample.zip](https://github.com/babel/babel-loader/files/197506/sample.zip)

**Comment by nevir** [comment] 2016-04-23 03:58
I'm seeing the same.  `transform-runtime` doesn't appear to remove `_interopRequireWildcard` declarations from the generated source, which appears to be the majority of duplication

**Comment by Maxpain177** [comment] 2016-05-21 18:12
+1

**Comment by Truedrog** [comment] 2016-05-30 16:06
Same here, i am compiling with transform runtime plugin and still have those helpers in each module file.

**Comment by ameyms** [comment] 2016-07-13 19:55
Did anyone manage to find a solution to this?

**Comment by frankLife** [comment] 2016-07-19 08:27
+ 1 , I find that more module(many bable-runtime/~/core-js/**/*.js) have been imported in build file .

**Comment by frankLife** [comment] 2016-08-02 15:03
@hzoo Could you give us some advice?

**Comment by RayForst** [comment] 2016-08-06 22:06
No solution yet?

**Comment by d3viant0ne** [comment] 2016-08-06 22:18
@jesprider - Thanks for providing the negative test case, it should make it far easier to track this down. I've thrown this on the `hotlist` and as such, the resolution will take priority.

Given me a day to get a few things in place & i'll see if I can get to the bottom or this. That said, given the obvious performance implications of that amount of duplication this certainly isn't working as intended.

**Comment by antitoxic** [comment] 2016-08-28 21:26
I will be happy with a workaround at the moment. Can I prevent babel from generating helpers' definitions and import helpers module manually for example? If yes, how?

cc @d3viant0ne

**Comment by antitoxic** [comment] 2016-08-29 07:15
Btw, to ease the pain of other devs and may be shine a light on what's working and what's not in `transform-runtime`, this is correctly externalizing helpers for me: https://github.com/brianZeng/babel-plugin-transform-helper

**Comment by antitoxic** [comment] 2016-11-05 12:31
@d3viant0ne is this ready in some beta version or is it blocked by something?

**Comment by mcjfunk** [comment] 2016-11-29 00:53
I figured out what's going on. The `babel-plugin-transform-runtime` plugin is correctly doing its business and the `babel-loader` is returning the correct source to webpack. But then webpack's module resolution begins and traces the dependencies within the source code, expanding them out. So in this case when `transform-runtime` adds `require("babel-runtime/helpers/createClass")` to the file, webpack says, "hey, let me find that dependency" finds it and expands it out to the final output, including what you were trying to exclude.

So the workaround is to add a regex to the webpack "externals" config with:

```
externals: [
    /^babel-runtime/
]
```

Then all is well.

It'd be nice if this could work as expected, but I'm not sure there is any mechanism for telling webpack to ignore resolving specific dependencies.

**Comment by nevir** [comment] 2016-12-01 20:00
Nice find!

**Comment by antitoxic** [comment] 2016-12-06 18:25
@mcjfunk Adding `/^babel-runtime/` breaks my output bundle. It seems to generate invalid javascript because I get `"SyntaxError: Unexpected token (8351:46)"` when using plugins that do AST parsing.

Did you do anything else?

**Comment by antitoxic** [comment] 2016-12-06 18:28
This is what I get in exports: `module.exports = babel-runtime/helpers/classCallCheck;`. No `require`s, just path. Strange.

**Comment by mcjfunk** [comment] 2016-12-08 15:14
I had to also add `libraryTarget: 'commonjs'` to the `output` object to get past the issue you are seeing.

**Comment by antitoxic** [comment] 2016-12-10 11:00
@mcjfunk can you post the entire config? Having `libraryTarget: 'commonjs'` isn't supposed to do much things.

**Comment by jeron-diovis** [comment] 2017-02-10 15:00
It seems that this is right place to post my issue.

With following configs:
```js
//.babelrc
{
  "presets": [
    "es2015"
  ],

  "plugins": [
    "transform-runtime"
  ]
}

// webpack
    loaders: [
      {
        test: /\.js$/i,
        loader: "babel-loader",
        exclude: /node_modules/,
      },
    ]

// dependencies
"babel-loader": "^6.2.10",
"babel-plugin-transform-runtime": "^6.22.0",
"webpack": "1.13.1",
```

I have in output bundle code like this:

```js
function(module, exports, __webpack_require__) {

    "use strict";

    import _Object$defineProperty from "babel-runtime/core-js/object/define-property";
    import _Object$keys from "babel-runtime/core-js/object/keys";
    ...
```

I.e., `transform-runtime` does it's job, but webpack somehow misses added `import` statements and does not transpiles them.

Could you please explain how to properly configure all this stuff?

**Comment by lookfirst** [comment] 2017-04-10 10:42
I created a super simple test project that shows pretty clearly that it isn't working right with all the latest versions of things. See enclosed.

`npm install && webpack`

Or just look at the enclosed output in the `dist` folder. You will note that there is a bunch of `require` lines at the top of `main.js` and near the bottom of `vendor.js`. The `babel-runtime` code isn't actually included anywhere.

[runtime-fail.zip](https://github.com/babel/babel-loader/files/909760/runtime-fail.zip)

Ideas appreciated!

**Comment by Apidcloud** [comment] 2017-06-02 15:05
I'm also having issues with **babel's** `transform-runtime` together with **webpack**.

I created a minimal repository to reproduce the problems:
https://github.com/Apidcloud/webpack-babel/

Basically, in order to support 'exports *' the option `modules `needs to be set to `false`. But after doing so, following error is raised:
`Cannot assign to read only property 'exports' of object`

Can someone take a look at the repository?

For some reason, if I have `ts-loader` (**typescript » es6 » es5**) on top of this setup, it works just fine.

Thanks!

**Comment by lookfirst** [comment] 2017-06-02 15:10
@Apidcloud I gave up and used the typescript compiler. Works great and as a bonus, I get typescript over ES6. ;-)

**Comment by Apidcloud** [comment] 2017-06-02 15:18
@lookfirst Yeah, it's an alternative, but not ideal in cases you want to use ES6 only.

It might be a problem with **webpack-dev-server** though.

**Comment by lookfirst** [comment] 2017-06-02 16:08
@Apidcloud 

I don't understand the `use ES6 only` statement as the TS compiler can parse ES6 code without problems. Your goal is to output ES5, you just need a transformer to do that.

If you download my runtime-fail.zip package above, the problem here has nothing to do with the server. It is just output generation.

**Comment by Apidcloud** [comment] 2017-06-02 19:32
@lookfirst I need both ES6 and ES5 outputs in my specific case.

The last issue I mention might be related with **webpack-dev-server**, but **transform-runtime** doesn't seem to be doing its work as well.

**Comment by Apidcloud** [comment] 2017-06-02 22:00
oh wow 😮 

So, I was able to fix the issues I was facing by **excluding** **node_modules** from webpack modules rules. I thought including a folder would basically result in the same thing, but it seems not!

You can check a working configuration at this repo:
https://github.com/Apidcloud/webpack-babel

It uses Webpack and Babel `transform-runtime`.

**Comment by paranoidjk** [comment] 2017-07-25 03:42
test with [rc-gesture](https://github.com/react-component/gesture)

## `npm run dist --babel-runtime`
generated rc-gesture.js 69.87kB
generated rc-gesture.js.map 89.58kB
generated rc-gesture.min.js 23.67kB

## `npm run dist`
generated rc-gesture.js 23.25kB
generated rc-gesture.js.map 21.93kB
generated rc-gesture.min.js 7.29kB

ref https://github.com/react-component/rc-tools/issues/37

**Comment by paranoidjk** [comment] 2017-07-25 05:19
cc @hzoo Could you have a look at this problem? 😄

**Comment by daurnimator** [comment] 2017-08-18 05:55
I'm having this issue as well. using `libraryTarget: commonjs` isn't an option for us: has anyone come up with a different workaround?

**Comment by lookfirst** [comment] 2017-08-18 07:47
TypeScript. =)

**Comment by BransonGitomeh** [comment] 2018-02-10 08:34
the only way i could get webpack to work well was telling it to target node 0.10, even in a browser environment...

**Comment by ctaylo21** [comment] 2018-04-11 21:03
This seems like a pretty big issue. I'm not sure why it hasn't got more traction if it really doesn't do what it's intended without a bunch of workarounds. I'm hoping I'm just doing something stupid. I'm using 

```
    "webpack": "^4.5.0",
    "@babel/runtime": "^7.0.0-beta.44"
    "@babel/preset-env": "^7.0.0-beta.44",
    "@babel/core": "^7.0.0-beta.44",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.44",
```

with a `.babelrc` of 

```
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": [
          "last 2 versions",
          "not IE <= 10"
        ]
      },
      "modules": false
    }]
  ],
  "plugins": ["@babel/plugin-transform-runtime"],
}
```

If I add a simple ES7 file like:
```
function sleep(duration) {
  return new Promise(function(resolve, reject) {
    setTimeout(()=> { resolve(0) }, duration);
  })
}

export async function delayedMessage(message, delay) {
  let remainingTime = await sleep(delay)
  console.log(message, `(remaining time: ${remainingTime})`)
}
```

and then use it in `index.js`:

```
import {delayedMessage} from './modules/delay.js'

delayedMessage("World", 400).then(()=>{ console.log('done') })
delayedMessage("Hello", 200)
```

When building with webpack 4, these are my results. 
**With plugin-transform-runtime**
![image](https://user-images.githubusercontent.com/1427469/38642916-6e9cbbb8-3d90-11e8-89d0-fdafdbbdb297.png)

**Without plugin-transform-runtime**
![image](https://user-images.githubusercontent.com/1427469/38642952-85325afe-3d90-11e8-821d-71e28eb3713f.png)

So the app size went from 4.29 KiB to 75.8KiB. What is happening? Am I using this wrong? 

I could understand if there might be a bit more code added to get the benefit of not affecting the global namespace. I assumed I might only see the benefit of consolidating all the inline helper methods to references to a single runtime module in a much larger app... but adding > 70KiB seems incredibly excessive.

**Comment by loganfsmyth** [comment] 2018-09-01 23:55
Hey all,
I believe the size issues here should be resolved in Babel 7. The reason it was so large in Babel 6 is because it also pulled in additional polyfilling logic, but in Babel 7 this requires opt-in behavior alongside `@babel/runtime-corejs2` instead of `@babel/runtime`.

**Closed by loganfsmyth** 2018-09-01 23:55 UTC
Labels: needs investigation, question

**Comment by cmdcolin** [comment] 2019-02-22 20:58
Sorry to necropost, but if you see this error, you might type "yarn why babel-core" or similar to see why an older package (babel-core which is v6) is included instead of (@babel/core which is v7). In my case I had @babel/core in my package.json but I had to "yarn add jest" to bump the jest version and get it to recognize it
