### ISSUE TITLE
How to output debug information?

### ISSUE THREAD

**Issue by josdejong** [babel/babel-loader#53] opened 2015-04-14 15:21 UTC
I'm using webpack and babel-loader in a gulpfile. In order to get errors in babel-loader reported, I've configured webpack with the options `{bail: true, debug: true}`. This works fine in that when any of my files contains an error, I get the error reported in the console.

However, I also have a `watch` task, which automatically runs on changes in any of the files. Problem now is that the watch task exits as soon as an error occurs, which sort of defeats the purpose of watch.

Is there a way to have error output in the console without exiting/crashing the webpack build task?

**Comment by Couto** [comment] 2015-04-14 21:45
Ideally you should use [webpack-dev-server](https://github.com/webpack/webpack-dev-server) to do the "watch" server

**Comment by josdejong** [comment] 2015-04-15 06:57
Thanks. That may solve this issue, though I rather keep things simple, with a small gulpfile and that's it. 

Would it be hard to extend `babel-loader` such that instead of silently failing, that it at least outputs errors? Right now I can only get errors reported by configuring webpack `{bail: true}`. But this also discontinues the build, which is undesired in the case of a watch task. The `{debug: true}` option of webpack does do nothing right now. Would it be possible to use the `debug` flag to output errors/warnings while *continuing* the process?

**Comment by Couto** [comment] 2015-04-15 07:45
The babel-loader is pretty much a simple wrapper around babel-core, so, as far as I can tell, your problem is with webpack itself and I believe that there's not much we can do.

However, if you know a webpack loader that respects the behavior that you're describing, please point me to it, since I'm quite willing to take a look at the code to improve things on this side :)

**Comment by josdejong** [comment] 2015-04-15 08:05
You can read the webpack config inside a loader via `this.options` (similar to `this.query`). So in order to check whether the global `debug` option is set to true, you could check `this.options.debug` and then have the loader write errors to the console.

**Comment by josdejong** [comment] 2015-04-15 08:07
btw shouldn't errors be outputted anyway, with or without a debug flag?

**Comment by josdejong** [comment] 2015-04-15 08:09
For inspiration you could have a look at [jshint-loader](https://github.com/webpack/jshint-loader), which supports extra options such as `emitErrors` and `failOnHint`.

**Comment by Couto** [comment] 2015-04-15 08:15
Thanks for the pointer, I took a quick look at jshint-loader, I think that I know what the problem is.
I will fix that later (currently at work) on the develop branch.

**Comment by josdejong** [comment] 2015-04-15 08:19
great, thanks beforehand!

**Comment by Couto** [comment] 2015-04-15 18:30
Can I ask you for a small test case? 
Mostly your Gruntfile and some code that should output an error, just so that I can have a test case similar to yours.

**Comment by josdejong** [comment] 2015-04-15 18:36
Yes sure, it's the v4 branch of the vis.js library: https://github.com/almende/vis/tree/v4

To reproduce: 
- clone the project
- run `npm install`
- introduce an error in one of the ES6 files, for example [uncomment line 5 here]( https://github.com/almende/vis/blob/v4/lib/network/modules/components/edges/BezierEdgeDynamic.js#L5) (that's where we stumbled upon)
- run `gulp watch` in the root of the project (takes in the order of 30 sec to run the first time)
- the webpack config is here: https://github.com/almende/vis/blob/v4/gulpfile.js#L37-L58. Note that right now both `debug` and `bail` is set to true, but ideally we would like to not set bail to true as it breaks the watch task...

Thanks!

**Comment by Couto** [comment] 2015-04-15 18:44
Ok looking at your code, and trying to provide the fastest solution possible:

webpack has ["hard" errors and "soft" errors](https://webpack.github.io/docs/node.js-api.html#error-handling), syntax errors thrown by babel are "soft" errors and therefore they don't break the build, if you want to output those, just add the following line next to [this](https://github.com/almende/vis/blob/de9334458b2cf14195e0138871a3dec76da328b0/gulpfile.js#L83)

```
if (stats.compilation.errors.length) {
 gutil.log(stats.compilation.errors[0].toString());
}
```
(I'm not a gulp user so take my example with a grain of salt)

I believe that this should output errors like you want to, without breaking the build.

I'll review the code for another solution :)

**Comment by josdejong** [comment] 2015-04-15 19:13
Thanks, this works! That's a nice workaround. 

I hope you can fine a good solution to output error logs by default, it's quite tricky not getting any error information in combination with webpack being silent about missing modules by default...

**Comment by josdejong** [comment] 2015-04-15 19:16
So I think you are right, this is a webpack issue and not a babel-loader issue: outputting these soft errors.

**Comment by Couto** [comment] 2015-04-15 19:32
I don't use gulp much, so I totally forgot that you have to use the compiler instance directly, which, in my opinion, makes you responsible to handle the errors, so I think my suggestion above is not a workaround, but the solution actually.

Still, I will try to improve the error handling, at least to log errors to the console if 'debug' is true.

**Comment by josdejong** [comment] 2015-04-15 19:37
Thanks, indeed handling the errors is up to the user. I just wish it was more trivial to get error output. Naively thinking you would expect to get output with `debug: true` you know ;)

**Comment by d3viant0ne** [comment] 2016-08-07 09:15
Resolving as multiple resolutions exist for the original issue.

**Closed by d3viant0ne** 2016-08-07 09:15 UTC
Labels: question, resolution in issue
