### ISSUE TITLE
Babel error on compilation Angular

### ISSUE THREAD

**Issue by subratbhola** [babel/babel-loader#973] opened 2022-11-07 07:38 UTC
Getting the same error with below mentioned configuration:
1. Angular 11
2. pdfMake: 0.1.71 and 0.2.4
3. node 10.21.0
4.  "@angular-devkit/build-angular": "~0.1102.13",

  "@babel/core": "7.12.10",
        "@babel/generator": "7.12.11",
        "@babel/plugin-transform-async-to-generator": "7.12.1",
        "@babel/plugin-transform-runtime": "7.12.10",
        "@babel/preset-env": "7.12.11",
        "@babel/runtime": "7.12.5",
        "@babel/template": "7.12.7",

Error: Module parse failed: Unexpected token (43456:116)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|            *     not null.
|            */
>           function gen_bitlen(s, desc) /*    deflate_state *s;*/ /*    tree_desc *desc;    /* the tree descriptor */*/{
|             var tree = desc.dyn_tree;
|             var max_code = desc.max_code;
Error: Module parse failed: Unexpected token (71044:112)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|        */
| 
>       function gen_bitlen(s, desc) /*    deflate_state *s;*/ /*    tree_desc *desc;    /* the tree descriptor */*/{
|         var tree = desc.dyn_tree;
|         var max_code = desc.max_code;

Team pdfMake , requesting you to share the feedback ASAP.

**Comment by JLHwung** [comment] 2022-11-07 15:21
Duplicate of https://github.com/babel/babel/issues/15132, this issue has been fixed in `@babel/generator` 7.20.3

**Closed by JLHwung** 2022-11-07 15:21 UTC
